<a href="https://colab.research.google.com/github/SunakshiRawat/python/blob/main/12_N2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
#np.transpose()

In [2]:
#Create a 2d array
two_d_array = np.array(np.random.randint(1,5,(2,5)))
print(f"the defined array is\n{two_d_array}")
print(f"\n the shape of the array is {two_d_array.shape}")

the defined array is
[[1 3 1 4 3]
 [4 1 1 1 1]]

 the shape of the array is (2, 5)


In [4]:
#Storing the transpose in another matrix object
another_two_d_array = np.transpose(two_d_array)
print(f" the transpose of the array is \n{another_two_d_array}")
print(f"\n the shape of the array is {another_two_d_array.shape}")

 the transpose of the array is 
[[1 4]
 [3 1]
 [1 1]
 [4 1]
 [3 1]]

 the shape of the array is (5, 2)


In [5]:
#Creating a 3d array
three_d_array = np.array(np.random.randint(1,6,(3,3,3)))
print(f"the defined array is\n{three_d_array}")
print(f"\n the shape of the array is {three_d_array.shape}")

the defined array is
[[[3 4 4]
  [3 2 1]
  [3 3 3]]

 [[1 4 5]
  [3 1 4]
  [4 1 5]]

 [[1 3 5]
  [1 2 4]
  [4 5 5]]]

 the shape of the array is (3, 3, 3)


In [6]:
#Storing the transpose of the created array
another_three_d_array = np.transpose(three_d_array)
print(f"the transpose the array is \n{three_d_array}")
print(f"\n the shape of the array is \n{another_three_d_array.shape}")

the transpose the array is 
[[[3 4 4]
  [3 2 1]
  [3 3 3]]

 [[1 4 5]
  [3 1 4]
  [4 1 5]]

 [[1 3 5]
  [1 2 4]
  [4 5 5]]]

 the shape of the array is 
(3, 3, 3)


In [15]:
#np.reshape()
random_two_d_array = np.array(np.random.randint(2,4,(2,6)))
print(f" the defined array is \n{random_two_d_array}")
print(f"\n the shape of the array is{random_two_d_array.shape}")

 the defined array is 
[[2 3 2 2 3 2]
 [3 3 3 3 2 3]]

 the shape of the array is(2, 6)


In [16]:
#Now we can reshape this to 1d,2d,3d array
new_shape = (2,2,3)
reshaped_random_two_d_array = np.reshape(random_two_d_array, new_shape)
print(f" the reshaped array is \n{reshaped_random_two_d_array}")
print(f"\n the shape of the array is{reshaped_random_two_d_array.shape}")

 the reshaped array is 
[[[2 3 2]
  [2 3 2]]

 [[3 3 3]
  [3 2 3]]]

 the shape of the array is(2, 2, 3)


In [23]:
new_shape = (3,2,2)
reshaped_random_two_d_array = np.reshape(random_two_d_array, new_shape)
print(f" the reshaped array is \n{reshaped_random_two_d_array}")
print(f" \n the shape of the array is{reshaped_random_two_d_array.shape}")

 the reshaped array is 
[[[2 3]
  [2 2]]

 [[3 2]
  [3 3]]

 [[3 3]
  [2 3]]]
 
 the shape of the array is(3, 2, 2)


In [26]:
#Create a 3d array
random_3d_array = np.array(np.random.randint(1,5,(3,3,2)))
print(f"the defined array is\n{random_3d_array}")
print(f"\n the shape of the array is {random_3d_array.shape}")

the defined array is
[[[2 3]
  [2 4]
  [4 3]]

 [[2 2]
  [1 4]
  [2 4]]

 [[1 4]
  [1 1]
  [4 3]]]

 the shape of the array is (3, 3, 2)


In [28]:
#Reshape the created 3d array
new_shape = (3,2,3)
reshaped_random_3d_array = np.reshape(random_3d_array, new_shape)
print(f" the reshaped array is \n{reshaped_random_3d_array}")
print("f\n the shape of the array is {reshaped_random_3d_array.shape}")

 the reshaped array is 
[[[2 3 2]
  [4 4 3]]

 [[2 2 1]
  [4 2 4]]

 [[1 4 1]
  [1 4 3]]]
f
 the shape of the array is {reshaped_random_3d_array.shape}


In [29]:
#np.resize(shape)
#Initialize a 3d array
random_3d_array = np.array(np.random.randint(1,5,(3,3,2)))
print(f"the defined array is\n{random_3d_array}")
print(f"\n the shape of the array is {random_3d_array.shape}")

the defined array is
[[[2 1]
  [1 3]
  [3 3]]

 [[1 4]
  [3 2]
  [4 3]]

 [[1 2]
  [3 4]
  [4 2]]]

 the shape of the array is (3, 3, 2)


In [30]:
#Resize the created 3d array
new_shape = (3,2,3)
resized_random_3d_array = np.resize(random_3d_array, new_shape)
print(f" the resized array is \n{resized_random_3d_array}")
print(f" \n the shape of the array is {reshaped_random_3d_array.shape}")

 the resized array is 
[[[2 1 1]
  [3 3 3]]

 [[1 4 3]
  [2 4 3]]

 [[1 2 3]
  [4 4 2]]]
 
 the shape of the array is (3, 2, 3)


In [32]:
random_3d_array.resize(new_shape)
random_3d_array

array([[[2, 1, 1],
        [3, 3, 3]],

       [[1, 4, 3],
        [2, 4, 3]],

       [[1, 2, 3],
        [4, 4, 2]]])

In [37]:
#np.flatten()
#Initialize a 3d array
random_3d_array = np.array(np.random.randint(1,5,(3,3,2)))
print(f"the defined array is\n{random_3d_array}")
print(f"\n the shape of the array is {random_3d_array.shape}")

the defined array is
[[[1 1]
  [3 1]
  [1 3]]

 [[3 1]
  [3 2]
  [4 3]]

 [[2 1]
  [1 4]
  [3 1]]]

 the shape of the array is (3, 3, 2)


In [39]:
#Flatten the 3d array
random_3d_array.flatten()

array([1, 1, 3, 1, 1, 3, 3, 1, 3, 2, 4, 3, 2, 1, 1, 4, 3, 1])

In [40]:
#Flattens the array in row-major order with 'c'
random_3d_array.flatten('c')

array([1, 1, 3, 1, 1, 3, 3, 1, 3, 2, 4, 3, 2, 1, 1, 4, 3, 1])

In [41]:
random_3d_array.flatten('f')

array([1, 3, 2, 3, 3, 1, 1, 4, 3, 1, 1, 1, 1, 2, 4, 3, 3, 1])

In [42]:
#np.insert(arr,obj,values,axis)
import numpy as np

a = np.random.randint(10,20,(2,3,4))
print(a)
print(a.shape)

[[[13 18 13 12]
  [14 18 17 13]
  [11 16 17 13]]

 [[13 14 19 17]
  [16 18 15 10]
  [14 19 12 12]]]
(2, 3, 4)


In [43]:
#Insert along axis=0
np.insert(a,1,100,axis=0)

array([[[ 13,  18,  13,  12],
        [ 14,  18,  17,  13],
        [ 11,  16,  17,  13]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 13,  14,  19,  17],
        [ 16,  18,  15,  10],
        [ 14,  19,  12,  12]]])

In [44]:
#Along axis=1
np.insert(a,0,50,axis=1)

array([[[50, 50, 50, 50],
        [13, 18, 13, 12],
        [14, 18, 17, 13],
        [11, 16, 17, 13]],

       [[50, 50, 50, 50],
        [13, 14, 19, 17],
        [16, 18, 15, 10],
        [14, 19, 12, 12]]])

In [45]:
#Along axis=2
np.insert(a,0,200,axis=2)

array([[[200,  13,  18,  13,  12],
        [200,  14,  18,  17,  13],
        [200,  11,  16,  17,  13]],

       [[200,  13,  14,  19,  17],
        [200,  16,  18,  15,  10],
        [200,  14,  19,  12,  12]]])

In [46]:
#np.append(arr,values,axis)

a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[3 2 2]
  [5 2 2]
  [2 2 5]]

 [[4 5 4]
  [2 2 2]
  [3 5 4]]]
(2, 3, 3)


In [49]:
#Append a value to the array. It flattens the array and append =99 to the end
np.append(a,50)

array([ 3,  2,  2,  5,  2,  2,  2,  2,  5,  4,  5,  4,  2,  2,  2,  3,  5,
        4, 50])

In [50]:
#Fix the axis other than axis of appending
b = np.random.randint(2,6,(2,1,3))
print(b)

[[[4 3 3]]

 [[3 4 4]]]


In [51]:
print(a)
print(a.shape)

[[[3 2 2]
  [5 2 2]
  [2 2 5]]

 [[4 5 4]
  [2 2 2]
  [3 5 4]]]
(2, 3, 3)


In [52]:
np.append(a,b,axis=1)

array([[[3, 2, 2],
        [5, 2, 2],
        [2, 2, 5],
        [4, 3, 3]],

       [[4, 5, 4],
        [2, 2, 2],
        [3, 5, 4],
        [3, 4, 4]]])

In [68]:
#np.delete(arr,pbj,axis)

a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[5 3 2]
  [3 4 4]
  [3 2 4]]

 [[3 4 5]
  [5 5 3]
  [2 4 3]]]
(2, 3, 3)


In [69]:
#Delete along axis=0
np.delete(a,(0), axis=0)

array([[[3, 4, 5],
        [5, 5, 3],
        [2, 4, 3]]])

In [70]:
#Delete along axis=1
np.delete(a,(0,2), axis=1)

array([[[3, 4, 4]],

       [[5, 5, 3]]])

In [71]:
a

array([[[5, 3, 2],
        [3, 4, 4],
        [3, 2, 4]],

       [[3, 4, 5],
        [5, 5, 3],
        [2, 4, 3]]])

In [72]:
#Delete along axis=2
np.delete(a,(0,1), axis=2)

array([[[2],
        [4],
        [4]],

       [[5],
        [3],
        [3]]])

In [73]:
#np.unique(arr,return_index,return_inverse,return_counts)
#Initialized array

a= np.random.randint(2,20,(2,3,3))
print(a)
print(a.shape)

[[[13 10 13]
  [16  3  8]
  [10 16  8]]

 [[15  2  2]
  [19  9  5]
  [18 18  8]]]
(2, 3, 3)


In [74]:
np.unique(a)

array([ 2,  3,  5,  8,  9, 10, 13, 15, 16, 18, 19])

In [75]:
#Return_counts = True
np.unique(a,return_counts=True)

(array([ 2,  3,  5,  8,  9, 10, 13, 15, 16, 18, 19]),
 array([2, 1, 1, 3, 1, 2, 2, 1, 2, 2, 1]))

In [76]:
#Return_index = True
np.unique(a,return_counts = True, return_index = True)

(array([ 2,  3,  5,  8,  9, 10, 13, 15, 16, 18, 19]),
 array([10,  4, 14,  5, 13,  1,  0,  9,  3, 15, 12]),
 array([2, 1, 1, 3, 1, 2, 2, 1, 2, 2, 1]))

In [77]:
#Lets take an example of a list

a = [1,2,3]
b=a
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[10, 2, 3]


In [78]:
#Lets use the copy method
a=[1,2,3]
b=a.copy()
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[1, 2, 3]


In [79]:
#Let us look at an array
a = np.array([2,34,12])
b=a
b[0] = -999
print(b)
print(a)

[-999   34   12]
[-999   34   12]


In [80]:
a = np.array([2,34,12])
b=a.copy()
b[0] = -999
print(b)
print(a)

[-999   34   12]
[ 2 34 12]


In [89]:
#Basic operations and functions
np.arange(3)

array([0, 1, 2])

In [90]:
np.arange(3) + 5

array([5, 6, 7])

In [91]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [92]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [93]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [98]:
np.ones((2,4)) + np.arange(4)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [100]:
np.arange(3).reshape((3,1))

array([[0],
       [1],
       [2]])

In [102]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [105]:
np.arange(3).reshape((3,1)) + np.arange(4)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [106]:
np.arange(2)

array([0, 1])

In [107]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(1,10,(2,2))
print(b)

[[2 3 3 3]
 [4 2 2 5]]
[[3 8]
 [6 8]]


In [109]:
#Multiplying two arrays
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(0,5,(2,4))
print(b)

[[4 3 3 2]
 [2 2 5 4]]
[[0 4 1 4]
 [0 2 2 1]]


In [110]:
np.multiply(a,b)

array([[ 0, 12,  3,  8],
       [ 0,  4, 10,  4]])

In [111]:
#Dividing two arrays
np.divide(a,b)

<ipython-input-111-59b6e7394f92>:2: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)


array([[ inf, 0.75, 3.  , 0.5 ],
       [ inf, 1.  , 2.5 , 4.  ]])

In [112]:
#Some aggregations operations

a = np.random.randint(5,9,(2,4))
print(a)

[[6 7 6 6]
 [5 5 8 6]]


In [115]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

49
[11 12 14 12]
[25 24]


In [117]:
#Calculate minimum
print(np.min(a))
print(np.min(a,axis=1))

5
[6 5]


In [118]:
#Sort the array
a = np.random.randint(0,20,(3,3))
print(a)

[[19  4  2]
 [ 4  5 13]
 [ 6 15 10]]


In [125]:
#Ascending columns
print(np.sort(a,axis=0))

[[ 4  4  2]
 [ 6  5 10]
 [19 15 13]]


In [126]:
#Ascending rows
print(np.sort(a,axis=1))

[[ 2  4 19]
 [ 4  5 13]
 [ 6 10 15]]


In [127]:
#Descending
print(-np.sort(-a,axis=1))

[[19  4  2]
 [13  5  4]
 [15 10  6]]


In [129]:
sum(np.arange(3)*np.arange(3).transpose())

5